steps:
  
# Install
- name: 'gcr.io/cloud-builders/yarn'
  args: ['yarn']

# Test
- name: 'gcr.io/cloud-builders/yarn'
  args: ['lint']

# Build
- name: 'gcr.io/cloud-builders/yarn'
  args: ['build']

# Build
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']