steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=myproject
  - --key=cloudbuild-env

# Install
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']
  
# # Install Nuxt
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install', '--save', 'nuxt']

# # Install
# - name: 'gcr.io/cloud-builders/yarn'

# # Build
# - name: 'gcr.io/cloud-builders/yarn'
#   args: ['build']

# Deploy
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'deploy']